# version: "1.0"
services:
  flask-app:
    image: hyd.ocir.io/axricq4df2uf/marketplace-bim-onboarding:${tag}
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: adibcontainer
    ports:
      - "2001:2001"
    restart: unless-stopped