# version: "1.0"
services:
  flask-app:
    build:
      context: ../adib-azure-restapi
      dockerfile: Dockerfile
    container_name: adibcontainer
    ports:
      - "2001:2001"
    restart: unless-stopped
